export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const OPEN_COMMENT_BOX = 'OPEN_COMMENT_BOX';
export const CLOSE_COMMENT_BOX = 'CLOSE_COMMENT_BOX';
export const SAVE_HIGHLIGHT = 'SAVE_HIGHLIGHT';
export const UPDATE_HIGHLIGHT = 'UPDATE_HIGHLIGHT';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
